dist: xenial
language: node_js

node_js:
  - "8"
  - "10"
  - "11"
  - "12"

install:
  - yarn

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  npm: true
  yarn: true
  directories:
    - node_modules

matrix:
  fast_finish: true
  allow_failures:
    - node_js: "12"

script:
  - yarn build:all
  - yarn test:acceptance:react:setup
  - yarn test
